auth0/node-jsonwebtoken

- README.md
- index.js
The message part of the JsonWebTokenError generated for `aud` and `iss` mismatch
currently use the [PAYLOAD AUDIENCE] and [PAYLOAD ISSUER] as the expected value.
This leads to confusion.  For example, say a JWT `aud` is set to
`https://localhost` and the expected value is `https://localhost:8443`. The
resulting error message is:
`jwt audience invalid. expected: https://localhost:8443`
Which of courses tells the user that the audience is incorrect, yet the expected
value is the value sent.
This commit changes the error message to use the actual expected values,
[OPTIONS AUDIENCE] and [OPTIONS ISSUER].
> Changes aud/iss error to use actual expected value

- index.js
- test/verify.tests.js
draft-ietf-oauth-json-web-token does not require JWT objects to have typ: "JWT"
in their header. Yet it expects that the JWT's claim set be JSON for validation.
See step 10 of draft-ietf-oauth-json-web-token section 7.2 "Validating a JWT".
Prior to this commit JWTs without typ: "JWT" in header are validated without
ever checking the claim set.
> First assume JWT claim set is an object

- .jshintrc
- index.js
- test/wrong_alg.tests.js
There is a vulnerability in this module when the verification part is expecting a token digitally signed with an asymetric key (RS/ES family) of algorithms but instead the attacker send a token digitally signed with a symmetric algorithm (HS* family).
The issue is because this library has the very same signature to verify both type of tokens (parameter: `secretOrPublicKey`).
This change adds a new parameter to the verify called `algorithms`. This can be used to specify a list of supported algorithms, but the default value depends on the secret used: if the secretOrPublicKey contains the string `BEGIN CERTIFICATE` the default is:
```
[ 'RS256','RS384','RS512','ES256','ES384','ES512' ]
``` 
otherwise is 
```
[ 'HS256','HS384','HS512' ]
````
> Verification with an asymmetric key of a token signed with a symmetric key

- index.js
- package.json
- test/jwt.rs.tests.js
- test/wrong_alg.tests.js
As `jws@3.0.0` changed the verify method signature to be `jws.verify(signature, algorithm, secretOrKey)`, the token header must be decoded first in order to make sure that the `alg` field matches one of the allowed `options.algorithms`. After that, the now validated `header.alg` is passed to `jws.verify`
As the order of steps has changed, the error that was thrown when the JWT was invalid is no longer the `jws` one:
```
{ [Error: Invalid token: no header in signature 'a.b.c'] code: 'MISSING_HEADER', signature: 'a.b.c' }
```
That old error (removed from jws) has been replaced by a `JsonWebTokenError` with message `invalid token`. That's why this change will bump be a major.
> Update to jws@^3.0.0

- README.md
The README currently links to https://github.com/auth0/node-jsonwebtoken/blob/master/auth0.com rather than https://auth0.com.
> Fix link to auth0.com in README

- README.md
- index.js
- test/jwt.rs.tests.js
This adds an option to return the header and payload when decoding a token.  The header includes claims such as `kid`, which is needed to support RS* signatures and key rotation, where keys are found in a JWKS.
This is needed for a forthcoming patch to express-jwt, in order to give the header claims to the `secretCallback`
> Add option to return header and payload when decoding.

- index.js
When .verify() a corrupted JWS (e.g.: malicious user add extra characters in the middle of token) an error is thrown:
``
[ERROR] console - SyntaxError: Unexpected token ͧ
at Object.parse (native)
at Object.jwsDecode [as decode] (/www/socketio-jwt/node_modules/jsonwebtoken/node_modules/jws/lib/verify-stream.js:71:20)
at Object.module.exports.verify (/www/socketio-jwt/node_modules/jsonwebtoken/index.js:120:26)`
``
Fix is similar to: https://github.com/auth0/node-jsonwebtoken/issues/14
> Avoid uncaught "SyntaxError: Unexpected token ͧ" error.

- README.md
Hi Team! 
Thanks for your work on this module. I found and fixed a simple, one-letter typo in the README. 
*From:*
complete: return an object with the **decode** payload and header.
*To:*
complete: return an object with the **decoded** payload and header.
Please let me know if I need to alter the PR in any way, glad to help.
> Fix typo, line 139 README, complete option for .decode.

- index.js
This commit allows you to assign the individual functions to variables, or in ES6 use [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) when importing the `jsonwebtoken` module. The only issue was the use of `this` in `decode()`, which has been changed to `module.exports`. 
The use of `this` in `decode()` caused the following error to occur.
```
TypeError: undefined is not a function
at module.exports.verify (/.../node_modules/jsonwebtoken/index.js:163:20)
```
ES5 code to cause error
```
var JWT = require("jsonwebtoken");
var sign = JWT.sign;
var verify = JWT.verify;
var secret = "test1234";
verify(sign({}, secret), secret);
```
ES6 code to cause error (tested with Babel)
```
import { verify, sign } from "jsonwebtoken"; …
```
> Fix this referring to the global object instead of module.exports in verify()

- index.js
- test/undefined_secretOrPublickey.tests.js
When secret or key fails to load or is not provided, `verify` can throw error even with callback.
Added check for `null` and `undefined`
> Empty secret or public key

- index.js
First of all `options.header` was never hit, if you follow the documentation and set your headers via `options.headers`:
```js
if (options.header) {
Object.keys(options.header).forEach(function (k) {
header[k] = options.header[k];
});
}
```
That would be easy to spot if you had a test coverage tool enabled in your build.
Next - even if you add **s** at the end of `options.header` you still can't override the `alg` header, because having this code:
```js
var header = ((typeof options.headers === 'object') && options.headers) || {};
header.alg = options.algorithm || 'HS256';
```
Actually modifies the `options.headers` before you have the chance to read its value. That's because `headers` is an object (pointer), not a value type.
So the test is pretty simple:
```js
jwt.sign({}, '', …
```
> Fix options.headers for the sign method

- index.js
- test/async_sign.tests.js
This PR addresses issue #106. Feedback would be appreciated, especially around whether the unit test is sufficient. Thanks!
> added async signing

- index.js
When used with browserify this causes a bug because the payload property is declared twice.
> Remove duplicate payload line (fix bug in IE strict mode)

- index.js
- test/async_sign.tests.js
- subscribe error event
- change the first argument of the callback as error
> feat: change .sign to standard async callback

- index.js
- test/verify.tests.js
`verify()` now accepts null for secretOrPublicKey if the token does not contain a signature. The default algorithm for unsigned tokens is `none`.
> Fix verification of unsigned tokens (fix #185)

- package.json
- sign.js
I am trying to get all our dependencies (including transient) to have proper license info, so we can automate the checking. We found that 'cb' doesn't have a license set (in the published version), and haven't seen any activity for over 3 years.
This switches to use lodash.once instead, which should be as small and as efficient.
> Use lodash.once instead of unlicensed/unmaintained cb

- test/verify.tests.js
- verify.js
This now works. The tests were wrongly putting typ: 'JWT' in the options instead of the header.
This caused jws.decode to not run a JSON parse. Now tests are passing fine.
Please also review the other tests that are putting typ: 'JWT' in the options. There is no point for that, as options.typ is not checked at all.
> Removed the double decoding

- sign.js
- test/keyid.tests.js
Identical to #249, but avoids unnecessary changes.
> Implemented keyid (kid) attribute in JWT header (Part II)

- .travis.yml
- package.json
~~Joi pre-v10 had an older, [vulnerable](https://snyk.io/vuln/npm:moment:20161019) version of moment as dependency, v10 no longer does.~~ (it's been pointed out to me that vulnerable moment was included due to another dependency locking the version down - Joi permits newer versions - but I think this PR still makes sense, as Joi 10 does not depend on moment at all) The breaking changes in v7 to v10 don't seem to be relevant to this codebase (other than introduction of ES6).
I also hope nobody minds that I updated the Travis setup to include latest versions of node and npm. This also removes node 0.12 from test matrix - Joi v7 deprecated that and v0.12 is EOL at the end of December anyways.
> Upgrade Joi dependency

- README.md
The ownership of this package has changed, see 301: https://github.com/rauchg/ms.js
> rauchg/ms.js changed to zeit/ms

- test/issue_304.tests.js
- verify.js
This PR adds handling of non string tokens, throwing a `JsonWebTokenError` error with `jwt malformed` message instead of `TypeError`.
Closes #304
> Fix handling non string tokens

- test/jwt.hs.tests.js
- verify.js
jws.decode() never throws an error. At least, in its current version. However, if it were to throw an exception, the diagnostics would be indistinguishable from a soft failure to decode a token. I had an extra trailing space on my JWT and it took me some additional debugging work to trace the actual root cause because the error message was not distinct.
> Raise jws.decode error to avoid confusion with "invalid token" error 

- README.md
- test/verify.tests.js
- verify.js
This PR enables passing a value `now` to the verify function that is then used instead of `Date.now()` (or rather `Math.floor(Date.now()/1000`).
Tackles https://github.com/auth0/node-jsonwebtoken/issues/240.
I didn't change the logic of `options.maxAge` because it uses milli seconds which seemed weird to use as a unit for `options.now`. (See https://github.com/auth0/node-jsonwebtoken/issues/273)
> Add clockTimestamp option to .verify() you can set the current time in seconds with it

- README.md
Fixes: https://github.com/auth0/node-jsonwebtoken/issues/350
> readme: Using private key with passpharase

- README.md
The keyid (`kid`) can be passed as an option to `sign()`, but it's not documented. 
https://github.com/auth0/node-jsonwebtoken/blob/master/sign.js#L59
> document keyid as option

- README.md
Closes https://github.com/auth0/node-jsonwebtoken/issues/208
> docs: verifying with base64 encoded secrets

- sign.js
- test/async_sign.tests.js
Lately there are more people raising this, not big deal but it can be weird and create confusion. We fix it in our layer, since the [bug in JWS is still open](https://github.com/brianloveswords/node-jws/issues/62).
In case of sync call, with current master code this error is returned: `TypeError: secret must be a string or buffer`.
With this PR both will return the same error `Error: secretOrPrivateKey must have a value`, I don't think the change would break anyone, because if someone got that error their integration would not be working at all.
Fixes: https://github.com/auth0/node-jsonwebtoken/issues/286
Fixes: https://github.com/auth0/node-jsonwebtoken/issues/373
> sign: add check to be sure secret has a value

- sign.js
- test/async_sign.tests.js
- test/jwt.hs.tests.js
Based on PR: https://github.com/auth0/node-jsonwebtoken/pull/382
Fix: https://github.com/auth0/node-jsonwebtoken/issues/381
It modifies @rhysmccaig approach to simply check the algorithm (`none`?) before raising an error. I think modifying the secret is hacky.
So this will reopen https://github.com/auth0/node-jsonwebtoken/issues/286 for the case of callback-ish code style and algorithm `none` (it didn't work before either). But it will solve the breaking change introduced by https://github.com/auth0/node-jsonwebtoken/pull/374
> Fix breaking change on 7.4.2 for empty secret + "none" algorithm (sync code style)

- sign.js
- test/async_sign.tests.js
Fix for https://github.com/auth0/node-jsonwebtoken/issues/381.
- When secret is Falsy, but algorithm is set to none, make secret a non zero length string before using jws.sign()/createSign()
- Added 2 unit tests
> Fix for #381. Set secret string before using jws when alg is none

- package.json
- sign.js
- test/expires_format.tests.js
- test/iat.tests.js
- test/schema.tests.js
As noted in #343 & #292 the specific version of `joi` is bloating the package size. However upgrading to the latest version would break ES5 compatibility. 
This PR shrinks the module size from **3.12M** to **0.25M** by replacing joi with bespoke implementation using lodash helpers.
N.B. To keep the implementation as simple as possible, these changes mean that the validation error messages are marginally less helpful e.g. -
`"expiresIn" must be a number` versus `"expiresIn" is not the correct type`
This should also solve #334.
> Remove joi to shrink module size

- verify.js
running synchronous code asynchronously using process.nextTick
has a negative latency impact
> verify: remove process.nextTick

- README.md
- test/verify.tests.js
- verify.js
Fixes [#346](https://github.com/auth0/node-jsonwebtoken/issues/346)
Fixes [#273](https://github.com/auth0/node-jsonwebtoken/issues/273).
Since this will expect seconds to be used (even using string type), I mark it for `next-major`.
> maxAge: Fix logic with number + use seconds instead of ms

- README.md
Fixes issue #385 , adds a few other definite articles for clarity.
> #385: Tweak README

- README.md
- test/jwt.asymmetric_signing.tests.js
- verify.js
The content of this pull request is to introduce the possibility to verify the audience against a regular expression.
The usage of this feature would be in a restrictive scenario where the audience needs to be verifiable against a large set of audiences because it has a parameter as part of the urn.
E.g.: Using a rest-endpoint to query all items of a specific order:
The endpoint listens to uris of the following structure: /Orders/:OrderId/Items
With the old implementation the audience could be verified against:
- a subset of the uri: '/Order/Items'
- an exhaustive list of permuatations ['/Order/1/Items', '/Order/2/Items', ... '/Order/1234/Items']
Or with the new implementation it can be verified against valid orderIds: ^\/Order\/\d{1,4}\/Items$
> Enhance audience check to verify against regular expressions

- package.json
[`zeit/ms@2.1.1`](https://github.com/zeit/ms) added full support for negative numbers, but the package is set to `zeit/ms@2.0.0`. This can be useful when defining a `nbf` value with `zeit/ms`, ie. `nbf = '-30m'`.
Due to npm's dependency de-duping this can sometimes result in this library using version `zeit/ms@2.0.0` instead of `zeit/ms@2.1.1` resulting in invalid results. In my case [`visionmedia/debug`](https://github.com/visionmedia/debug) had their version on `zeit/ms` pinned to `2.0.0`.
This PR bumps the version to `zeit/ms@2.1.1` to ensure that negative numbers in `zeit/ms` format work as expected.
```
$ npm show ms version
2.1.1
$ npm list ms
@org/auth-lib@1.0.0 /Users/mitmaro/code/org/auth-lib
├─┬ debug@3.1.0
│ └── ms@2.0.0
└─┬ jsonwebtoken@8.1.0
└── ms@2.0.0  deduped
```
> Bump ms version to add support for negative numbers

- sign.js
- test/iat.tests.js
See #435 
Set nbf value based on the timestamp.
> Not Before (nbf) calculated based on iat/timestamp

- README.md
- sign.js
- test/async_sign.tests.js
The `mutatePayload` option allows you to get an updated reference to the raw token payload after claims have been applied to it but before it has been encoded. Default behaviour is unchanged since `mutatePayload` defaults to false.
Added tests.
Closes https://github.com/auth0/node-jsonwebtoken/issues/357
Another simple (maybe more elegant) solution could have been to pass the signed-but-not-encoded payload as an extra argument to the callback but that wouldn't work with the synchronous version of the function.
> Add a new mutatePayload option

- README.md
It does kinda go without saying that JWTs (_JSON_ Web Tokens) need to contain JSON but it's worth mentioning that signing doesn't check your payload.  In some unit tests I was writing where the payload was a dummy (non-JSON parsable) string, JWTs were being signed okay but they're not valid according to the spec, which caused decoding of the JWTs to later fail.
> Clarify in README that buffer/string payloads must be JSON

- .travis.yml
`before_install` script downloads npm@6 by default now.
Probably it is not needed to enforce the installation of npm in `before_install` script, removing it.
Failure:
```
$ node --version
v4.9.1
$ npm --version
2.15.11
$ nvm --version
0.33.11
before_install
14.92s$ npm i -g npm
/home/travis/.nvm/versions/node/v4.9.1/bin/npm -> /home/travis/.nvm/versions/node/v4.9.1/lib/node_modules/npm/bin/npm-cli.js
/home/travis/.nvm/versions/node/v4.9.1/bin/npx -> /home/travis/.nvm/versions/node/v4.9.1/lib/node_modules/npm/bin/npx-cli.js
npm@6.0.1 /home/travis/.nvm/versions/node/v4.9.1/lib/node_modules/npm
3.35s$ npm install 
/home/travis/.nvm/versions/node/v4.9.1/lib/node_modules/npm/bin/npm-cli.js:79
let notifier = require('update-notifier')({pkg})
^^^
SyntaxError: Block-scoped declarations (let, …
```
> travis ci fix for node 4 and 5 builds

- README.md
Modify README to avoid issues like:
- https://github.com/auth0/node-jsonwebtoken/issues/463
- https://github.com/auth0/node-jsonwebtoken/issues/456
- https://github.com/auth0/node-jsonwebtoken/issues/451
> readme: add some clarifications

- .editorconfig
- .eslintrc
- README.md
- package.json
- sign.js
- test/keyid.tests.js
- test/verify.tests.js
- verify.js
Based on [PR 413](https://github.com/auth0/node-jsonwebtoken/pull/413), without breaking existing functionality.
Added features
- verify's secretOrToken parameter can now be a callback function, see updated README.md for details
- updated tests and readme
Performance improvements
- merged two decodes into one
Dependencies
- Removed xtend and use Object.assign instead
See issue [406](https://github.com/auth0/node-jsonwebtoken/issues/406)
> Secret callback revisited

- .gitignore
- package.json
While looking to add tests for PR 413 i noticed it would be helpful to have an overview of the tested code. Hopefully this helps :)
> Added Istanbul to check test-coverage

- package.json
- test/iat.tests.js
- test/jwt.asymmetric_signing.tests.js
- test/nbf.test.js
- test/schema.tests.js
- test/verify.tests.js
First PR for #492.
This change extracts all tests in the current files related to `notBefore` and `nbf` into a single test file. It also adds several missing related tests.
I believe I removed all references to `nbf` and `notBefore` from the current tests.
~~There are two TODOs in the tests, because I found a few unhandled cases that I expected would cause an error but did not. They are:~~
* ~~Passing an empty string to `notBefore`. I'm not sure if this should default to `0` or should throw an error. Currently it throws a `val is not a non-empty string or a valid number. val=""` from `ms`.~~
* ~~Passing `-Infinity`, `Infinity` and `NaN` to `nbf`. These all `JSON.stringify` to `null`, so I would assume should be considered invalid.~~
Any suggestions of missing tests are more than welcome, …
> Refactor tests related to notBefore and nbf (#492)

- test/claim-sub.tests.js
- test/jwt.asymmetric_signing.tests.js
- test/schema.tests.js
For #492 
This change extracts all tests in the existing files related to the subject option and sub claim into a single test file. Several other tests are also added that were missing from the existing files.
I removed all references to "subject" and "sub" from the existing test files that I could find.
There seems to be only minimal validation on the subject claim. The next major version could handle adding validation to this claim.
As always, suggestions or missing tests are welcome!
```
```
``` …
```
> Refactor tests related to subject and sub

- test/claim-iat.test.js
- test/option-maxAge.test.js
- test/schema.tests.js
- test/verify.tests.js
For #492 
This change extracts all tests related to the `iat` claim and the `maxAge` verify option into two test files. Several additional tests are added that were missing from the existing tests.
Most of the references to `iat` have been removed from the existing tests. The remaining references are not directly related to the `iat` claim.
Unlike the previous test pull requests, this pull request adds some validation tests for `maxAge` to a separate file, since the option isn't directly related to a claim.
As always, suggestions or missing tests are welcome!
``` …
```
> Refactor tests related to iat and maxAge

- package.json
- test/async_sign.tests.js
Update [chai to 4.1.2](https://github.com/chaijs/chai/releases/tag/4.1.2) and mocha to the latest versions and update nyc to the latest version that supports Node 4.
I keep hitting minor differences with `chai@1`, with the documentation for `chai@4`. There are also numerous bug fixes and additions that we are missing out with this library. The only breaking change as it relates to this code base is the [removal of the "lint" friendly assertions](https://github.com/chaijs/chai/pull/306) in `chai@2`.
`Mocha@2` had a "fuzzy" version of the `.only` function that made running individual tests almost impossible without artificially changing the description (i.e. `describe.only('xxxx expires' //....`). There are no breaking changes that should affect the project.
> Update dependencies used for running tests

- test/claim-iat.test.js
- test/test-utils.js
For #492 
In #507 there was a comment about creating a utility function to help with testing both the asynchronous and synchronous calls to `sign` and `verify`. This is the concept that I came up with based on that comment. If this is accepted I will update the existing refactored tests to use the helpers.
```
```
```
Lines …
```
> Create and implement async/sync test helpers

- README.md
`NotBeforeError` is not documented in the list of errors that can be thrown from `verify`.
> Document NotBeforeError

- sign.js
- test/claim-exp.test.js
For #492 
This implements the test helpers introduced in #523 for the exp claim.
There was one test case that required a code change. When the expiry is provided using an empty string, the error is thrown synchronously during an asynchronous call. This error is already triggered by another error (#499), so I believe it is okay to fix the handling of this error even if it is a slight behavior change.
```
```
``` …
```
> Implement async/sync tests for exp claim

- sign.js
- test/claim-nbf.test.js
For #492 
This implements the test helpers introduced in #523 for the nbf claim.
There was one test case that required a code change. When the not before is provided using an empty string, the error is thrown synchronously during an asynchronous call. This error is already triggered by another error (#499) and similar to #536, so I believe it is okay to fix the handling of this error even if it is a slight behaviour change.
```
Statements   : 97.89% ( 232/237 )
Lines        : 98.29% ( 230/234 )
```
```
=============================== Coverage summary …
```
> Implement async/sync tests for nbf claim

- test/claim-aud.test.js
For #492 
This implements the test helpers introduced in #523 for the aud claim. I also parameterized some of the test cases in an attempt to simplify them.
```
```
```
```
> Implement async/sync tests for the aud claim

- sign.js
- test/claim-exp.test.js
- test/claim-nbf.test.js
This PR fixes TODO items to change error message when empty string passed as `expiresIn` or `notBefore` options
> Fixed error message when empty string passed as expiresIn or notBefore option

- test/header-kid.test.js
- test/keyid.tests.js
- test/schema.tests.js
Next PR for #492 
This change extracts all tests in the existing test files related to `kid` and `keyid` into a single test file. Several other tests are also added that were missing from the existing files.
All references to `keyid` and `kid` have been removed from the existing test files.
As always, suggestions or missing tests are more than welcome!
```
Statements   : 97.07% ( 232/239 )
Branches     : 97.57% ( 201/206 )
Lines        : 97.46% ( 230/236 )
```
```
Statements   : 97.07% ( 232/239 )
Branches     : 97.57% ( …
```
> Refactor tests related to kid and keyid

- README.md
- test/option-nonce.test.js
- verify.js
I want to verify nonce value in jwt.
Then I found the following pull request.
https://github.com/auth0/node-jsonwebtoken/pull/344
But because tests and README have not been added, it has not yet been merged.
So I did add tests and README.
> Add verify option for nonce validation

- test/claim-jti.test.js
- test/jwt.asymmetric_signing.tests.js
Next PR for #492 
This change extracts all tests in the existing test files related to `jwtid` and `jti` into a single test file. Several other tests are also added that were missing from the existing files.
All references to `jwtid` and `jti` have been removed from the existing test files.
As always, suggestions or missing tests are more than welcome!
```
Statements   : 97.07% ( 232/239 )
Branches     : 97.57% ( 201/206 )
Lines        : 97.46% ( 230/236 )
```
```
Statements   : 97.07% ( 232/239 )
Branches     : 97.57% ( …
```
> Refactor tests related to jti and jwtid

- test/claim-private.tests.js
Another PR for #492
This change adds tests for private claims added to the payload during sign and ensures that after verifying the payload contains the expected claim. There are not currently any dedicated tests to private claims, so these test cases are new.
```
Statements   : 96.72% ( 236/244 )
Branches     : 97.21% ( 209/215 )
Lines        : 97.1% ( 234/241 )
```
```
Statements   : 96.72% ( 236/244 )
Branches     : 97.21% ( 209/215 )
Lines        : 97.1% ( 234/241 ) …
```
> Add tests for private claims in the payload

- README.md
Certs have pubkeys. We sign things with private keys.
> Fix 'cert' token which isn't a cert

- package.json
- sign.js
- test/claim-iat.test.js
Our project was using JS strict mode and we got errors like
```
TypeError: Cannot create property 'iat' on string
```
Enabling `--use_strict` during the mocha test revealed the culprit.
> Force use_strict during testing

- .travis.yml
- README.md
- lib/psSupported.js
- package.json
- sign.js
- test/async_sign.tests.js
- test/jwt.asymmetric_signing.tests.js
- test/rsa-public-key.tests.js
- test/schema.tests.js
- test/wrong_alg.tests.js
- verify.js
the PS family of JSON Web Algorithms is supported in node.js versions ^6.12.0, not 7, and then >=8
> feat: add PS JWA support

- package.json
Bumps the `jws` version to ensure correct `jwa` implementation of PS algorithms is used.
- https://github.com/brianloveswords/node-jws/issues/85
- https://github.com/brianloveswords/node-jwa/pull/34
> fix: ensure correct PS signing and verification

- README.md
Adds a note to the README that suggest that decoded payload should not be trusted and should be treated as user inputs therefore avoiding using unchecked attribute merging functions with the returned decoded payload.
Closes #639
> Adds note to README on decoded payload validation

- README.md
This PR updates only docs. I added `jwtid` to options of jwt.verify on README.md.
`jwtid` is implemented [here](https://github.com/auth0/node-jsonwebtoken/blob/master/verify.js#L187-L191) as one of jwt.verify options.
Closes #581 
- ~~[ ] This change adds test coverage for new/changed/fixed functionality~~ => This PR updates only docs.
> docs: add jwtid to options of jwt.verify

- README.md
- index.js
Address what was shared here - https://github.com/auth0/node-jsonwebtoken/pull/741#issuecomment-687349482
> Update docs to make sure decode is less discoverable

- README.md
Fix simple misspelling of `peek` in the README.md. You peek inside a token.
> docs: fix spelling in README.md: Peak -> Peek

- README.md
Adds `'invalid token'` to the list of error messages and explains the difference between that and `'jwt malformed'`
https://github.com/auth0/node-jsonwebtoken/issues/768
> docs: document "invalid token" error

- README.md
Zeit is now Vercel, so just updated those references in the README to be current.
https://vercel.com/blog/zeit-is-now-vercel
> docs: update references vercel/ms references

- .circleci/config.yml
- README.md
- package.json
- sign.js
- test/async_sign.tests.js
- test/jwt.hs.tests.js
- test/jwt.malicious.tests.js
- test/rsa-public-key.tests.js
- test/schema.tests.js
- verify.js
- Added checks to prevent invalid secrets from being used with the HS*** algorithms when signing and verifying
- Added checks to prevent the use of insecure asymmetric key sizes except when explicitly overriden via options
BREAKING CHANGE: Requires node 12.x or later to allow use of `KeyObject`
This PR covers addresses 3 misconfigurations which could compromise security.
1. Signing with a public key that has a modulus length of less than 2048 is …
> fix!: Prevent accidental use of insecure key sizes & misconfiguration of secrets

- .github/workflows/ci.yml
- .github/workflows/semgrep.yml
This PR aims to be the first PR in replacing circle CI with Github Actions (the next PR will remove .circleci once we know this is working). this PR adds two jobs for running the tests and [semgrep (a security scanning tool)](https://semgrep.dev/).
N/A
> chore(ci): configure Github Actions jobs for Tests & Security Scanning

- CHANGELOG.md
- package.json
Releasing `9.0.1` which closes https://github.com/auth0/node-jsonwebtoken/pull/876
- https://github.com/auth0/node-jsonwebtoken/pull/876
> Updating package version to 9.0.1

- package.json
This PR updates [semver](https://www.npmjs.com/package/semver) to a minimum version of 7.5.4 to resolve CVE-2022-25883.
- CVE-2022-25883
- https://github.com/auth0/node-jsonwebtoken/issues/921
- https://github.com/auth0/node-jsonwebtoken/pull/919
- ✅  `npm test` is passing.
- ✅  This change adds test coverage for new/changed/fixed functionality
> security: updating semver to 7.5.4 to resolve CVE-2022-25883

- package.json
- sign.js
This is to reduce the size of the bundle users have to install.
In 9.0.0 we introduced a change which depended on lodash as a whole, which meant our bundle size increased. We need to ensure our bundle size is small enough so customers can depend on it at the edge for serverless functions.
- https://github.com/auth0/node-jsonwebtoken/pull/916
- https://github.com/auth0/node-jsonwebtoken/issues/878
- https://github.com/auth0/node-jsonwebtoken/pull/852
- ✅ …
> refactor: reduce library size by using lodash specific dependencies

- CHANGELOG.md
- package.json
- Updates changelog to include #933 and #932 
- Updates version to 9.0.2.
- #933 
- #932 
Test coverage already covers the changes, and we have tested the changes in the referenced PRs.
> Update package.json and changelog for release 9.0.2
